# Board Config
BOARD_HEIGH = 15
BOARD_WIDTH = 20


# Ships Config
SMALL_SHIP_SIZE = 2
MEDIUM_SHIP_SIZE = 3
LARGE_SHIP_SIZE = 4
AMOUNT_OF_SMALL_SHIPS = 5
AMOUNT_OF_MEDIUM_SHIPS = 3
AMOUNT_OF_LARGE_SHIPS = 2


# User
USER_NAME = "PLAYER"  # Default name is user will not set anything
