# Board Config
BOARD_HEIGH = 15
BOARD_WIDTH = 20


# Ships Config
SMALL_SHIP_SIZE = 2
MEDIUM_SHIP_SIZE = 3
LARGE_SHIP_SIZE = 4
AMOUNT_OF_SMALL_SHIPS = 4  # 5
AMOUNT_OF_MEDIUM_SHIPS = 2  # 3
AMOUNT_OF_LARGE_SHIPS = 1  # 2


# User
USER_NAME = "PLAYER"  # Default name is user will not set anything
BOT_NAME = "BOT"

SPACES_BETWEEN_OTHER_BOARD = 8

SPACE_BETWEEN_TITLES = (
    3 * (BOARD_WIDTH) - len(USER_NAME) + SPACES_BETWEEN_OTHER_BOARD + 5
)

BOT_THINK = " "
